# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
Team.create!([
  { name: "Buffalo Bills", wins: 0, losses: 0 },
  { name: "Miami Dolphins", wins: 0, losses: 0 },
  { name: "New England Patriots", wins: 0, losses: 0 },
  { name: "New York Jets", wins: 0, losses: 0 },
  { name: "Baltimore Ravens", wins: 0, losses: 0 },
  { name: "Pittsburgh Steelers", wins: 0, losses: 0 },
  { name: "Cleveland Browns", wins: 0, losses: 0 },
  { name: "Cincinnati Bengals", wins: 0, losses: 0 },
  { name: "Houston Texans", wins: 0, losses: 0 },
  { name: "Tennessee Titans", wins: 0, losses: 0 },
  { name: "Jacksonville Jaguars", wins: 0, losses: 0 },
  { name: "Indianapolis Colts", wins: 0, losses: 0 },
  { name: "Las Vegas Raiders", wins: 0, losses: 0 },
  { name: "Denver Broncos", wins: 0, losses: 0 },
  { name: "Kasas City Chiefs", wins: 0, losses: 0 },
  { name: "Los Angeles Chargers", wins: 0, losses: 0 },
  { name: "Washington Football Team", wins: 0, losses: 0 },
  { name: "Dallas Cowboys", wins: 0, losses: 0 },
  { name: "New York Giants", wins: 0, losses: 0 },
  { name: "Chicago Bears", wins: 0, losses: 0 },
  { name: "Detroit Lions", wins: 0, losses: 0 },
  { name: "Green Bay Packers", wins: 0, losses: 0 },
  { name: "Minnesota Vikings", wins: 0, losses: 0 },
  { name: "Tampa Bay Buccaneers", wins: 0, losses: 0 },
  { name: "Carolina Panthers", wins: 0, losses: 0 },
  { name: "New Orleans Saints", wins: 0, losses: 0 },
  { name: "San Francisco 49ers", wins: 0, losses: 0 },
  { name: "Los Angeles Rams", wins: 0, losses: 0 },
  { name: "Arizona Cardinals", wins: 0, losses: 0 },
  { name: "Seattle Seahawks", wins: 0, losses: 0 },
])
