# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
Team.create!([
  { city: "Buffalo", name: "Bills", wins: 0, losses: 0, ties: 0, division: "East", conference: "AFC", image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Ffreebiesupply.com%2Flogos%2Fbuffalo-bills-logo%2F&psig=AOvVaw1BgXAmwNIzvtKCpB3gSshK&ust=1642638325054000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMjx4OjGvPUCFQAAAAAdAAAAABAD" },
  { city: "Miami", name: "Dolphins", wins: 0, losses: 0, ties: 0, division: "East", conference: "AFC", image: "https://wallpaperaccess.com/full/3643021.jpg" },
  { city: "New England", name: "Patriots", wins: 0, losses: 0, ties: 0, division: "East", conference: "AFC", image: "https://static.clubs.nfl.com/image/private/f_auto/patriots/ftuml6gmogyahtnd2neb" },
  { city: "New York", name: "Jets", wins: 0, losses: 0, ties: 0, division: "East", conference: "AFC", image: "https://cdn.mos.cms.futurecdn.net/kBd6mdRHDBMzhPTZhNXu9Z-1200-80.jpg" },
  { city: "Baltimore", name: "Ravens", wins: 0, losses: 0, ties: 0, division: "North", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/05/Baltimore-Ravens-emblem.jpg" },
  { city: "Pittsburgh", name: "Steelers", wins: 0, losses: 0, ties: 0, division: "North", conference: "AFC", image: "https://i.ebayimg.com/images/g/jt4AAOSwTP5hmEBS/s-l300.png" },
  { city: "Cleveland", name: "Browns", wins: 0, losses: 0, ties: 0, division: "North", conference: "AFC", image: "https://cloudfront-us-east-1.images.arcpublishing.com/gray/PB2EJMCWG5BBTD6JOO22CZUK24.jpg" },
  { city: "Cincinnati", name: "Bengals", wins: 0, losses: 0, ties: 0, division: "North", conference: "AFC", image: "https://static.clubs.nfl.com/image/private/t_editorial_landscape_12_desktop/bengals/vfz5dedg5uxvafqhnvoj.jpg" },
  { city: "Houston", name: "Texans", wins: 0, losses: 0, ties: 0, division: "South", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/05/Houston-Texans-symbol.jpg" },
  { city: "Tennessee", name: "Titans", wins: 0, losses: 0, ties: 0, division: "South", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/05/Tennessee-Titans-symbol.jpg" },
  { city: "Jacksonville", name: "Jaguars", wins: 0, losses: 0, ties: 0, division: "South", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/05/Jacksonville-Jaguars-logo.png" },
  { city: "Indianopolis", name: "Colts", wins: 0, losses: 0, ties: 0, division: "South", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/05/Indianapolis-Colts-Logo.png" },
  { city: "Las Vegas", name: "Raiders", wins: 0, losses: 0, ties: 0, division: "West", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Las-Vegas-Raiders-Logo.png" },
  { city: "Denver", name: "Broncos", wins: 0, losses: 0, ties: 0, division: "West", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Denver-Broncos-Logo.png" },
  { city: "Los Angeles", name: "Chargers", wins: 0, losses: 0, ties: 0, division: "West", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Los-Angeles-Chargers-Logo.png" },
  { city: "Kansas City", name: "Chiefs", wins: 0, losses: 0, ties: 0, division: "West", conference: "AFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Kansas-City-Chiefs-Logo.png" },
  { city: "Washington", name: "Football Team", wins: 0, losses: 0, ties: 0, division: "East", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Washington-Football-Team-Logo.png" },
  { city: "Dallas", name: "Cowboys", wins: 0, losses: 0, ties: 0, division: "East", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Dallas-Cowboys-Logo.png" },
  { city: "New York", name: "Giants", wins: 0, losses: 0, ties: 0, division: "East", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/New-York-Giants-Team-Logo.png" },
  { city: "Philadelphia", name: "Eagles", wins: 0, losses: 0, ties: 0, division: "East", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Philadelphia-Eagles-Logo.png" },
  { city: "Chicago", name: "Bears", wins: 0, losses: 0, ties: 0, division: "North", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Chicago-Bears-Logo.png" },
  { city: "Detroit", name: "Lions", wins: 0, losses: 0, ties: 0, division: "North", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Detroit-Lions-Logo.png" },
  { city: "Green Bay", name: "Packers", wins: 0, losses: 0, ties: 0, division: "North", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Green-Bay-Packers-Logo.png" },
  { city: "Minnesota", name: "Vikings", wins: 0, losses: 0, ties: 0, division: "North", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Minnesota-Vikings-Logo.png" },
  { city: "Tampa Bay", name: "Buccaneers", wins: 0, losses: 0, ties: 0, division: "South", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Tampa-Bay-Buccaneers-Logo.png" },
  { city: "Carolina", name: "Panthers", wins: 0, losses: 0, ties: 0, division: "South", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Carolina-Panthers-Logo.png" },
  { city: "New Orleans", name: "Saints", wins: 0, losses: 0, ties: 0, division: "South", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/New-Orleans-Saints-Logo.png" },
  { city: "Atlanta", name: "Falcons", wins: 0, losses: 0, ties: 0, division: "South", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Atlanta-Falcons-Logo.png" },
  { city: "San Francisco", name: "49ers", wins: 0, losses: 0, ties: 0, division: "West", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/San-Francisco-49ers-Logo.png" },
  { city: "Seattle", name: "Seahawks", wins: 0, losses: 0, ties: 0, division: "West", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Seattle-Seahawks-Logo.png" },
  { city: "Los Angeles", name: "Rams", wins: 0, losses: 0, ties: 0, division: "West", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Los-Angeles-Rams-Logo.png" },
  { city: "Arizona", name: "Cardinals", wins: 0, losses: 0, ties: 0, division: "West", conference: "NFC", image: "https://logos-world.net/wp-content/uploads/2020/06/Arizona-Cardinals-Logo.png" },
])
